### ISSUE TITLE
脚本生成的config.json配置文件有个小错误

### ISSUE THREAD

**Issue by karlh4ever** [Libunko/v2ray_cli#1]
v2ray在执行时会报错，我根据提示，把outbounds的“port” : "1234" 改成 "port" : 1234 ，把"alterId" : "2" 改成 "alterId" : 2 才能正常使用，也就是去掉冒号。我不懂python，没办法直接修改脚本。所以想请您修改。

v2ray reports an error during execution. According to the prompt, I changed the "port": "1234" to "port": 1234 and changed "alterId": "2" to "alterId": 2 in outbounds section, it works fine. That means, the colon should be removed for nomal use. I'm not familiar with python, can't modify the script by myself. So I would like to ask you to fix this problem. Thanks for your great works!

**Comment by Libunko** [comment]
估计是订阅源端格式导致，已修复。
