### ISSUE TITLE
Error out if node name contains special characters

### ISSUE THREAD

**Issue by hailinzeng** [Libunko/v2ray_cli#3]
v2ray_cli/subscribe.py", line 60, in show
    print("%d\t%s" % (num,item))
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 2-5: surrogates not allowed

**Comment by hailinzeng** [comment]
If the node name contains emoji

🇭🇰IEPL-香港 -5

**Comment by hailinzeng** [comment]
-            print("%d\t%s" % (num, item))
    +            print("%d\t%s" % (num,item.encode('utf-16', 'surrogatepass').decode('utf-16')))

    -        print("Node Selected: %s" % name)
    +        print("Node Selected: %s" % name.encode('utf-16', 'surrogatepass').decode('utf-16'))

one possible solution: https://stackoverflow.com/a/38147966/732267

**Comment by Libunko** [comment]
My subscription link does not have the Emoji character. I haven't tried it, but thank you~
